kind: pipeline
name: default

steps:
  - name: docker push
    image: plugins/docker
    settings:
      repo: eignhpants/gif-factory
      username:
        from_secret: dh-username
      password:
        from_secret: dh-pw
    publish:
      image: eignhpants/gif-factory
